#!/usr/bin/env python3
"""Rebuild the mean-rank records of Tables 4-5 from the per-seed records (no model is run).

  python reproduction/rebuild_ranks.py

Reads  reproduction/per_seed_k20.csv (192 rows: 8 settings x 8 methods x seeds 20/21/22)
Writes reproduction/means_unrounded_k20.csv, column_ranks_k20.csv, mean_rank_by_backbone.csv,
       MEAN_RANK_K20.md (Tables 4-5 layout: displayed value and rank per column)

The three seeds are averaged first (unrounded); every accuracy column is ranked within its
setting on the displayed four-decimal mean, equal displayed values sharing the average rank
(analysis/common.py: display, display_ranks -- the functions analysis/collect_results.py
uses).  The mean rank averages 6 columns for MF / LightGCN and 4 for SimGCL.
"""
import os
import sys

import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(os.path.dirname(HERE), 'analysis'))
from common import display_ranks, check_records, MAIN_ARMS, RANK_COLUMNS, CELL_ORDER  # noqa: E402

METRICS = ['recall20', 'ndcg20']


def main():
    seeds = pd.read_csv(os.path.join(HERE, 'per_seed_k20.csv'))
    problems = check_records(seeds, arm_col='method', keys=('dataset', 'backbone'))
    if problems or len(seeds) != 192:
        raise SystemExit('per_seed_k20.csv: %d rows\n%s' % (len(seeds), '\n'.join(problems)))
    means = seeds.groupby(['dataset', 'backbone', 'method']).agg(
        n_seeds=('seed', 'count'), recall20=('recall20', 'mean'), ndcg20=('ndcg20', 'mean')).reset_index()
    means.to_csv(os.path.join(HERE, 'means_unrounded_k20.csv'), index=False, float_format='%.10f')

    ranked, mr = display_ranks(means, METRICS, ['dataset', 'backbone'], arm_col='method')
    cols = []
    for m in METRICS:
        c = ranked[['dataset', 'backbone', 'method']].copy()
        c.insert(2, 'metric', m)
        c['value'] = ranked[m].map(lambda v: '%.10f' % v)
        c['displayed'] = ranked['disp_' + m]
        c['rank'] = ranked['rank_' + m]
        cols.append(c)
    cols = pd.concat(cols).sort_values(['dataset', 'backbone', 'metric', 'method'], kind='stable')
    cols.to_csv(os.path.join(HERE, 'column_ranks_k20.csv'), index=False)

    mr = mr.rename(columns={'mean_rank_n_cols': 'n_cols'})[['backbone', 'method', 'n_cols', 'mean_rank']]
    mr = mr.sort_values(['backbone', 'method'], kind='stable')
    bad = mr[mr.n_cols != mr.backbone.map(RANK_COLUMNS)]
    if not bad.empty:
        raise SystemExit('unexpected number of rank columns:\n%s' % bad.to_string(index=False))
    mr.to_csv(os.path.join(HERE, 'mean_rank_by_backbone.csv'), index=False)

    short = {'Amazon-VG': 'VG', 'Amazon-Movies': 'Movies', 'Douban-movie': 'Douban'}
    md = ['# Mean rank of Tables 4-5 (test @20, three-seed means)', '',
          'Ranks are computed from the displayed four-decimal three-seed mean values, with average ranks',
          'assigned to ties.  Generated by `reproduction/rebuild_ranks.py` from `per_seed_k20.csv`.', '']
    for bb in ('MF', 'LightGCN', 'SimGCL'):
        dss = [d for d, b in CELL_ORDER if b == bb]
        md += ['## %s' % bb, '', '| Method | ' + ' | '.join('%s %s (rank)' % (short[d], m) for d in dss for m in ('R@20', 'N@20')) + ' | mean rank |',
               '|---' * (2 * len(dss) + 2) + '|']
        for arm in MAIN_ARMS:
            cells = []
            for d in dss:
                r = ranked[(ranked.dataset == d) & (ranked.backbone == bb) & (ranked.method == arm)].iloc[0]
                cells += ['%s (%g)' % (r['disp_' + m], r['rank_' + m]) for m in METRICS]
            v = mr[(mr.backbone == bb) & (mr.method == arm)].iloc[0]
            md.append('| %s | %s | %.2f (n=%d) |' % (arm, ' | '.join(cells), v.mean_rank, v.n_cols))
        md.append('')
    with open(os.path.join(HERE, 'MEAN_RANK_K20.md'), 'w') as f:
        f.write('\n'.join(md) + '\n')

    ties = cols[cols.duplicated(['dataset', 'backbone', 'metric', 'displayed'], keep=False)]
    print('per-seed rows: %d; seeds 20/21/22 complete for %d methods in %d settings' % (
        len(seeds), len(MAIN_ARMS), seeds.groupby(['dataset', 'backbone']).ngroups))
    print('\nequal displayed values (average rank):')
    print(ties.to_string(index=False) if not ties.empty else '  none')
    print('\nmean rank (rows: method; columns: backbone)')
    print(mr.pivot(index='method', columns='backbone', values='mean_rank').loc[MAIN_ARMS].round(2).to_string())


if __name__ == '__main__':
    main()
